---
name: zls
description: Zig LSP implementation + Zig Language Server.
homepage: https://github.com/zigtools/zls
licenses:
  - MIT
languages:
  - Zig
categories:
  - LSP

  # TODO: map from zig version to latest zls version for zig build?
  # ZLS nightly index:
  # https://zigtools-releases.nyc3.digitaloceanspaces.com/zls/index.json

source:
  zig_version: 0.12.0-dev.2341+92211135f
  id: pkg:generic/zls@{{zig_version}}
  download:
    - target: darwin_arm64
      files:
        bin: https://zigtools-releases.nyc3.digitaloceanspaces.com/zls/0.12.0-dev.2341+92211135f/aarch64-macos/zls

schemas:
  lsp: vscode:https://raw.githubusercontent.com/ziglang/vscode-zig/master/package.json

bin:
  zls: "{{source.download.files.bin}}"
